[pytest]
testpaths = tests
python_files = test_*.py
addopts = --verbose --cov=core --cov=ui --cov-report=term-missing --cov-report=html
bdd_features_base_dir = tests/
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
